//! WinUI 3 host (proof of concept, feature `winui`): the same window, layout and text measuring as
//! the Win32 host, rendered by a XAML island instead of Direct2D. Every laid-out node becomes an
//! absolutely positioned element on one `Canvas` (`Border` for fills, `TextBlock` for text,
//! `TextBox` for inputs), reused across commits when the element kinds line up.
//!
//! Needs the Windows App SDK runtime (framework package) and
//! `Microsoft.WindowsAppRuntime.Bootstrap.dll` next to the executable.
//! `bindings.rs` is generated by windows-bindgen 0.65 from the Windows App SDK metadata for the
//! types in `types.txt` (and their dependencies).

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals, dead_code, clippy::all)]
mod bindings;

use bindings::Microsoft::UI::Dispatching::DispatcherQueueController;
use bindings::Microsoft::UI::Xaml::Controls::{Border, Canvas, TextBlock, TextBox, TextChangedEventHandler, XamlControlsResources};
use bindings::Microsoft::UI::Xaml::Hosting::{DesktopWindowXamlSource, WindowsXamlManager};
use bindings::Microsoft::UI::Xaml::Input::KeyEventHandler;
use bindings::Microsoft::UI::Xaml::Media::SolidColorBrush;
use bindings::Microsoft::UI::Xaml::{Application, CornerRadius, ResourceDictionary, UIElement};
use bindings::Microsoft::UI::WindowId;
use tishlang_ms_common::layout::{font, padding};
use tishlang_ms_common::style::{props_color, props_f64, props_string, Rgba};
use tishlang_ms_common::tree::{Node, Rect};
use windows::core::{Interface, HSTRING, PCSTR};
use windows::Graphics::RectInt32;
use windows::Win32::Foundation::HWND;
use windows::Win32::System::LibraryLoader::{GetProcAddress, LoadLibraryW};
use windows::UI::Color;

/// Called with (input index, text) when a TextBox changes, and with a virtual-key code on a key
/// press (true: handled).
pub(crate) struct Hooks {
    pub on_text: fn(usize, String),
    pub on_key: fn(u16) -> bool,
}

enum Elem {
    Fill(Border),
    Text(TextBlock),
    Input(TextBox),
}

impl Elem {
    fn kind(&self) -> u8 {
        match self {
            Elem::Fill(_) => 0,
            Elem::Text(_) => 1,
            Elem::Input(_) => 2,
        }
    }

    fn ui(&self) -> windows::core::Result<UIElement> {
        match self {
            Elem::Fill(b) => b.cast(),
            Elem::Text(t) => t.cast(),
            Elem::Input(t) => t.cast(),
        }
    }
}

pub(crate) struct Xaml {
    _queue: DispatcherQueueController,
    _app: Application,
    _manager: WindowsXamlManager,
    source: DesktopWindowXamlSource,
    canvas: Canvas,
    elems: Vec<Elem>,
    hooks: &'static Hooks,
    dark: bool,
}

#[repr(C)]
struct PackageVersion {
    version: u64,
}

type MddBootstrapInitialize2 = unsafe extern "system" fn(u32, *const u16, PackageVersion, u32) -> windows::core::HRESULT;

/// Windows App SDK 2.5 (WindowsAppSDK-VersionInfo.h), or any later 2.x the bootstrapper finds.
const MAJOR_MINOR: u32 = 0x0002_0005;
const MIN_RUNTIME: u64 = 0x0002_0005_0001_0000;

/// Find the Windows App SDK runtime for this process (unpackaged apps).
fn bootstrap() -> Result<(), String> {
    unsafe {
        let lib = LoadLibraryW(&HSTRING::from("Microsoft.WindowsAppRuntime.Bootstrap.dll"))
            .map_err(|e| format!("Microsoft.WindowsAppRuntime.Bootstrap.dll: {e}"))?;
        let f = GetProcAddress(lib, PCSTR(c"MddBootstrapInitialize2".as_ptr().cast())).ok_or("no MddBootstrapInitialize2")?;
        let init: MddBootstrapInitialize2 = std::mem::transmute(f);
        let tag = [0u16];
        init(MAJOR_MINOR, tag.as_ptr(), PackageVersion { version: MIN_RUNTIME }, 0)
            .ok()
            .map_err(|e| format!("the Windows App SDK 2.5 runtime isn't installed: {e}"))
    }
}

fn color(c: Rgba) -> Color {
    let b = |v: f32| (v.clamp(0.0, 1.0) * 255.0).round() as u8;
    Color { A: b(c.a), R: b(c.r), G: b(c.g), B: b(c.b) }
}

fn brush(c: Rgba) -> windows::core::Result<SolidColorBrush> {
    SolidColorBrush::CreateInstanceWithColor(color(c))
}

fn place(e: &UIElement, r: Rect) -> windows::core::Result<()> {
    Canvas::SetLeft(e, r.x)?;
    Canvas::SetTop(e, r.y)?;
    Ok(())
}

impl Xaml {
    pub(crate) fn attach(hwnd: HWND, dark: bool, hooks: &'static Hooks) -> Result<Self, String> {
        bootstrap()?;
        let e = |e: windows::core::Error| e.to_string();
        let queue = DispatcherQueueController::CreateOnCurrentThread().map_err(e)?;
        // An island needs a XAML Application on the thread, with WinUI's control styles in its
        // resources (TextBox and friends have no template without them).
        let app = match Application::Current() {
            Ok(a) => a,
            Err(_) => Application::new().map_err(|x| format!("Application: {x}"))?,
        };
        let styles: ResourceDictionary = XamlControlsResources::new().map_err(|x| format!("XamlControlsResources: {x}"))?.cast().map_err(e)?;
        app.Resources().and_then(|r| r.MergedDictionaries()).and_then(|m| m.Append(&styles)).map_err(|x| format!("merging the control styles: {x}"))?;
        let manager = WindowsXamlManager::InitializeForCurrentThread().map_err(e)?;
        let source = DesktopWindowXamlSource::new().map_err(e)?;
        source.Initialize(WindowId { Value: hwnd.0 as u64 }).map_err(e)?;
        let canvas = Canvas::new().map_err(e)?;
        source.SetContent(&canvas).map_err(e)?;
        let handler = KeyEventHandler::new(move |_, args| {
            if let Some(a) = args.as_ref() {
                if (hooks.on_key)(a.Key()?.0 as u16) {
                    a.SetHandled(true)?;
                }
            }
            Ok(())
        });
        canvas.PreviewKeyDown(&handler).map_err(e)?;
        Ok(Self { _queue: queue, _app: app, _manager: manager, source, canvas, elems: Vec::new(), hooks, dark })
    }

    /// The island fills the client area (`w` × `h` physical pixels).
    pub(crate) fn resize(&self, w: i32, h: i32) {
        if let Ok(bridge) = self.source.SiteBridge() {
            let _ = bridge.MoveAndResize(RectInt32 { X: 0, Y: 0, Width: w, Height: h });
        }
    }

    fn make(&self, kind: u8, input_index: usize) -> windows::core::Result<Elem> {
        Ok(match kind {
            0 => Elem::Fill(Border::new()?),
            1 => Elem::Text(TextBlock::new()?),
            _ => {
                let tb = TextBox::new()?;
                let hooks = self.hooks;
                let i = input_index;
                tb.TextChanged(&TextChangedEventHandler::new(move |sender, _| {
                    if let Some(s) = sender.as_ref() {
                        let t: TextBox = s.cast()?;
                        (hooks.on_text)(i, t.Text()?.to_string());
                    }
                    Ok(())
                }))?;
                Elem::Input(tb)
            }
        })
    }

    /// Mirror the laid-out tree: one element per fill, text and input, in tree order.
    pub(crate) fn commit(&mut self, roots: &[Node]) -> windows::core::Result<()> {
        let mut nodes = Vec::new();
        for r in roots {
            r.walk(&mut nodes);
        }
        let children = self.canvas.Children()?;
        let mut i = 0;
        let mut inputs = 0;
        for n in nodes {
            let bg = props_color(&n.props, &["backgroundColor", "background"]).filter(|c| c.a > 0.0);
            let mut want: Vec<(u8, Rect)> = Vec::new();
            match n.tag.as_str() {
                "rule" => want.push((0, Rect { h: 1.0, ..n.frame })),
                "image" if n.frame.h > 1.0 => want.push((0, Rect { w: n.frame.h.min(n.frame.w), ..n.frame })),
                _ if bg.is_some() => want.push((0, n.frame)),
                _ => {}
            }
            match n.tag.as_str() {
                "text" | "button" if !n.text.is_empty() => want.push((1, n.frame)),
                "textinput" => want.push((2, n.frame)),
                _ => {}
            }
            for (kind, r) in want {
                if i >= self.elems.len() || self.elems[i].kind() != kind {
                    let el = self.make(kind, inputs)?;
                    if i >= self.elems.len() {
                        children.Append(&el.ui()?)?;
                        self.elems.push(el);
                    } else {
                        children.SetAt(i as u32, &el.ui()?)?;
                        self.elems[i] = el;
                    }
                }
                self.update(i, n, r, bg)?;
                if kind == 2 {
                    inputs += 1;
                }
                i += 1;
            }
        }
        while self.elems.len() > i {
            children.RemoveAtEnd()?;
            self.elems.pop();
        }
        // Measure and arrange now, so a commit's cost includes XAML's layout pass.
        self.canvas.UpdateLayout()
    }

    fn update(&self, i: usize, n: &Node, r: Rect, bg: Option<Rgba>) -> windows::core::Result<()> {
        let text_color = props_color(&n.props, &["color"]).unwrap_or(if self.dark { Rgba { r: 0.95, g: 0.95, b: 0.95, a: 1.0 } } else { Rgba { r: 0.1, g: 0.1, b: 0.1, a: 1.0 } });
        match &self.elems[i] {
            Elem::Fill(b) => {
                let c = match n.tag.as_str() {
                    "rule" => props_color(&n.props, &["color"]).unwrap_or(Rgba { r: 0.5, g: 0.5, b: 0.5, a: 0.3 }),
                    "image" => Rgba { r: 0.5, g: 0.5, b: 0.5, a: 0.35 },
                    _ => bg.unwrap_or(Rgba { r: 0.0, g: 0.0, b: 0.0, a: 0.0 }),
                };
                b.SetBackground(&brush(c)?)?;
                let rad = if n.tag == "image" { r.w / 5.0 } else { props_f64(&n.props, &["borderRadius", "cornerRadius"], 0.0) };
                b.SetCornerRadius(CornerRadius { TopLeft: rad, TopRight: rad, BottomRight: rad, BottomLeft: rad })?;
                b.SetWidth(r.w)?;
                b.SetHeight(r.h)?;
                place(&b.cast()?, r)?;
            }
            Elem::Text(t) => {
                let (pt, pr, _, pl) = padding(&n.props);
                let f = font(&n.props);
                t.SetText(&HSTRING::from(n.text.as_str()))?;
                t.SetFontSize(f.size)?;
                t.SetFontWeight(windows::UI::Text::FontWeight { Weight: f.weight })?;
                t.SetForeground(&brush(text_color)?)?;
                t.SetWidth((r.w - pl - pr).max(0.0))?;
                place(&t.cast()?, Rect { x: r.x + pl, y: r.y + pt, ..r })?;
            }
            Elem::Input(tb) => {
                let f = font(&n.props);
                if let Some(v) = props_string(&n.props, &["value"]) {
                    if tb.Text()?.to_string() != v {
                        tb.SetText(&HSTRING::from(v.as_str()))?;
                        tb.SetSelectionStart(v.encode_utf16().count() as i32)?;
                    }
                }
                if let Some(p) = props_string(&n.props, &["placeholder"]) {
                    tb.SetPlaceholderText(&HSTRING::from(p.as_str()))?;
                }
                tb.SetFontSize(f.size)?;
                tb.SetWidth(r.w)?;
                tb.SetHeight(r.h)?;
                place(&tb.cast()?, r)?;
            }
        }
        Ok(())
    }

    pub(crate) fn focus_input(&self) {
        for e in &self.elems {
            if let Elem::Input(tb) = e {
                let _ = tb.Focus(bindings::Microsoft::UI::Xaml::FocusState::Programmatic);
                return;
            }
        }
    }
}
